#!/bin/sh
  
set -e
set -u

: "${UID:=0}"
: "${GID:=${UID}}"

if [ "$#" = 0 ]
then set -- "$(command -v bash 2>/dev/null || command -v sh)" -l
fi

if [ "$UID" != 0 ]
then
        set -- gosu "${UID}:${GID}" env HOME="/home/$DOCKER_USER" "${@}"
else
        export HOME=/root
fi

exec "$@"
