#!/bin/sh
# kvmhwd Rev2.0

start_usb_dev(){
    . /etc/profile
    echo "usb mode: device"
    cd /sys/kernel/config/usb_gadget

    mkdir g0
    cd g0

    echo 0x3346 > idVendor
    echo 0x1009 > idProduct
    mkdir strings/0x409
    echo '0123456789ABCDEF' > strings/0x409/serialnumber
    echo 'sipeed' > strings/0x409/manufacturer
    echo 'NanoKVM' > strings/0x409/product

    mkdir configs/c.1
    echo 0xE0 > configs/c.1/bmAttributes
    echo 120 > configs/c.1/MaxPower
    mkdir configs/c.1/strings/0x409
    echo "NanoKVM" >  configs/c.1/strings/0x409/configuration

    if [ -e /boot/usb.ncm ]
    then
        mkdir functions/ncm.usb0
        ln -s functions/ncm.usb0 configs/c.1/
    else
        if [ -e /boot/usb.rndis0 ]
        then
                mkdir functions/rndis.usb0
                ln -s functions/rndis.usb0 configs/c.1/
        fi
    fi

    if [ ! -e /boot/disable_hid ]
    then
        # keyboard
        mkdir functions/hid.GS0
        if [ -e /boot/BIOS ]
        then
            echo 1 > functions/hid.GS0/subclass
        fi
        if [ ! -e /boot/usb.notwakeup ]
        then
            echo 1 > functions/hid.GS0/wakeup_on_write
        fi
        echo 1 > functions/hid.GS0/protocol
        echo 6 > functions/hid.GS0/report_length
        echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.GS0/report_desc
        ln -s functions/hid.GS0 configs/c.1

        # mouse
        mkdir functions/hid.GS1
        if [ -e /boot/BIOS ]
        then
            echo 1 > functions/hid.GS1/subclass
        fi
        if [ ! -e /boot/usb.notwakeup ]
        then
            echo 1 > functions/hid.GS1/wakeup_on_write
        fi
        echo 2 > functions/hid.GS1/protocol
        echo -ne \\x34 > functions/hid.GS1/report_length
        echo -ne \\x5\\x1\\x9\\x2\\xa1\\x1\\x9\\x1\\xa1\\x0\\x5\\x9\\x19\\x1\\x29\\x3\\x15\\x0\\x25\\x1\\x95\\x3\\x75\\x1\\x81\\x2\\x95\\x1\\x75\\x5\\x81\\x3\\x5\\x1\\x9\\x30\\x9\\x31\\x9\\x38\\x15\\x81\\x25\\x7f\\x75\\x8\\x95\\x3\\x81\\x6\\xc0\\xc0 > functions/hid.GS1/report_desc        
        ln -s functions/hid.GS1 configs/c.1

        # touchpad
        mkdir functions/hid.GS2
        if [ -e /boot/BIOS ]
        then
            echo 1 > functions/hid.GS2/subclass
        fi
        if [ ! -e /boot/usb.notwakeup ]
        then
            echo 1 > functions/hid.GS2/wakeup_on_write
        fi
        echo 2 > functions/hid.GS2/protocol
        echo 6 > functions/hid.GS2/report_length
        echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x01\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x00\\x26\\xff\\x7f\\x35\\x00\\x46\\xff\\x7f\\x75\\x10\\x95\\x02\\x81\\x02\\x05\\x01\\x09\\x38\\x15\\x81\\x25\\x7f\\x35\\x00\\x45\\x00\\x75\\x08\\x95\\x01\\x81\\x06\\xc0\\xc0 > functions/hid.GS2/report_desc
        ln -s functions/hid.GS2 configs/c.1
    fi

    if [ -e /boot/usb.disk0 ]
    then
            mkdir functions/mass_storage.disk0
            ln -s functions/mass_storage.disk0 configs/c.1/
            echo 1 > functions/mass_storage.disk0/lun.0/removable
            if [ -e /boot/usb.disk0.ro ]
            then
                    echo 1 > functions/mass_storage.disk0/lun.0/ro
                    echo 0 > functions/mass_storage.disk0/lun.0/cdrom
            fi
            disk=$(cat /boot/usb.disk0)
            if [ -z "${disk}" ]
            then
                    # if [ ! -e /mnt/usbdisk.img ]
                    # then
                    #         fallocate -l 8G /mnt/usbdisk.img
                    #         mkfs.vfat /mnt/usbdisk.img
                    # fi
                    echo /dev/mmcblk0p3 > functions/mass_storage.disk0/lun.0/file
            else
                    cat /boot/usb.disk0 > functions/mass_storage.disk0/lun.0/file
            fi
    fi

    ls /sys/class/udc/ | cat > UDC
    echo device > /proc/cviusb/otg_role
}

start_usb_host(){
    echo '' > /sys/kernel/config/usb_gadget/g0/UDC
    echo host > /proc/cviusb/otg_role
}

restart_usb_dev(){
    echo > /sys/kernel/config/usb_gadget/g0/UDC
    sleep 1
    ls /sys/class/udc/ | cat > /sys/kernel/config/usb_gadget/g0/UDC
    echo "USB Restart OK!"
}

case "$1" in
  start)
    start_usb_dev
  ;;
  restart)
    restart_usb_dev
  ;;
  stop)
    start_usb_host
  ;;
  stop_start)
    start_usb_host
    start_usb_dev
  ;;
esac
