#!/bin/sh
# kvmhwd Rev2.2

# shellcheck source=/kvmapp/system/init.d/S03usb-common
. "${USB_COMMON:-/kvmapp/system/init.d/S03usb-common}"

USB_NCM_FUNC='ncm.usb0'
USB_RNDIS_FUNC='rndis.usb0'
USB_MASS_STORAGE_FUNC='mass_storage.disk0'
USB_MASS_STORAGE_INQUIRY='NanoKVM USB Mass Storage0520'
USB_LEGACY_EMPTY_DISK_BACKING='/dev/mmcblk0p3'
USB_BASE_UID="${USB_BASE_UID:-/sys/class/cvi-base/base_uid}"

set_network_macs(){
    func="functions/$1"
    usb_uid=$(sha512sum "${USB_BASE_UID}" 2>/dev/null | head -c 4)
    [ -n "${usb_uid}" ] || return 0

    printf '%s' "48:da:35:6e:${usb_uid%??}:${usb_uid#??}" > "${func}/dev_addr"
    printf '%s' "48:da:35:6d:${usb_uid%??}:${usb_uid#??}" > "${func}/host_addr"
}

start_usb_dev(){
    prepare_usb_gadget "${USB_NORMAL_BCD_USB}" "${USB_NORMAL_BCD_DEVICE}" "${USB_NORMAL_CONFIG_ATTRIBUTES}" "${USB_NORMAL_MAX_POWER}"

    echo 0xEF > bDeviceClass
    echo 0x02 > bDeviceSubClass
    echo 0x01 > bDeviceProtocol

    if [ -e "${USB_BOOT_DIR}/usb.ncm" ]
    then
        mkdir "functions/${USB_NCM_FUNC}"
        set_network_macs "${USB_NCM_FUNC}"
        echo WINNCM > "functions/${USB_NCM_FUNC}/os_desc/interface.ncm/compatible_id"
        ln -s "functions/${USB_NCM_FUNC}" configs/c.1/
    elif [ -e "${USB_BOOT_DIR}/usb.rndis0" ]
    then
        mkdir "functions/${USB_RNDIS_FUNC}"
        set_network_macs "${USB_RNDIS_FUNC}"
        echo e0 > "functions/${USB_RNDIS_FUNC}/class"
        echo 01 > "functions/${USB_RNDIS_FUNC}/subclass"
        echo 03 > "functions/${USB_RNDIS_FUNC}/protocol"
        echo RNDIS > "functions/${USB_RNDIS_FUNC}/os_desc/interface.rndis/compatible_id"
        echo 5162001 > "functions/${USB_RNDIS_FUNC}/os_desc/interface.rndis/sub_compatible_id"
        ln -s "functions/${USB_RNDIS_FUNC}" configs/c.1/
    fi

    if [ -e "${USB_BOOT_DIR}/usb.ncm" ] || [ -e "${USB_BOOT_DIR}/usb.rndis0" ]
    then
        echo 1 > os_desc/use
        echo 0xCD > os_desc/b_vendor_code
        echo MSFT100 > os_desc/qw_sign
        ln -s configs/c.1 os_desc
    fi

    if [ ! -e "${USB_BOOT_DIR}/disable_hid" ]
    then
        add_hid_functions "${USB_HID_REPORT_NORMAL_KEYBOARD}" "${USB_HID_REPORT_NORMAL_ABSOLUTE_MOUSE}"
    fi

    if [ -e "${USB_BOOT_DIR}/usb.disk0" ]
    then
        mkdir "functions/${USB_MASS_STORAGE_FUNC}"
        ln -s "functions/${USB_MASS_STORAGE_FUNC}" configs/c.1/
        echo 1 > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/removable"
        if [ -e "${USB_BOOT_DIR}/usb.disk0.ro" ]
        then
            echo 1 > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/ro"
            echo 0 > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/cdrom"
        fi
        echo "${USB_MASS_STORAGE_INQUIRY}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/inquiry_string"
        disk=$(cat "${USB_BOOT_DIR}/usb.disk0")
        if [ -z "${disk}" ]
        then
            # if [ ! -e /mnt/usbdisk.img ]
            # then
            #         fallocate -l 8G /mnt/usbdisk.img
            #         mkfs.vfat /mnt/usbdisk.img
            # fi
            echo "${USB_LEGACY_EMPTY_DISK_BACKING}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/file"
        else
            printf '%s' "${disk}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/file"
        fi
    fi

    bind_first_udc
}

run_usb_action "$1"
