#!/bin/sh
# kvmhwd hid only

# shellcheck source=/kvmapp/system/init.d/S03usb-common
. "${USB_COMMON:-/kvmapp/system/init.d/S03usb-common}"

start_usb_dev(){
    prepare_usb_gadget "${USB_HID_ONLY_BCD_USB}" "${USB_HID_ONLY_BCD_DEVICE}" "${USB_HID_ONLY_CONFIG_ATTRIBUTES}" "${USB_HID_ONLY_MAX_POWER}"
    add_hid_functions "${USB_HID_REPORT_HID_ONLY_KEYBOARD}" "${USB_HID_REPORT_HID_ONLY_ABSOLUTE_MOUSE}"
    bind_first_udc
}

run_usb_action "$1"
