#!/bin/sh

. /etc/profile

APFLAG_FILE=/tmp/wifiap
WIFI_STATIC_CONFIG=/boot/wifi.nodhcp

escape_wpa_value() {
    printf "%s" "$1" | tr -d '\r\n' | sed 's/\\/\\\\/g; s/"/\\"/g'
}

sanitize_wpa_token() {
    printf "%s" "$1" | tr -cd 'A-Za-z0-9_-'
}

clean_line() {
    echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/\r//g'
}

append_wpa_field() {
    key="${1}"
    value="${2}"
    if [ -n "$value" ]; then
        printf '    %s="%s"\n' "$key" "$(escape_wpa_value "$value")"
    fi
}

calc_gw() {
    addr="$1"
    netid="$2"
    IFS=. read a b c d <<EOF
$addr
EOF
    ipnum=$(( (a<<24) + (b<<16) + (c<<8) + d ))
    mask=$(( 0xFFFFFFFF << (32-netid) & 0xFFFFFFFF ))
    gwnum=$(( (ipnum & mask) | 1 ))
    if [ $gwnum -eq $ipnum ]; then
        broadcast=$(( (ipnum & mask) | (0xFFFFFFFF & ~mask) ))
        gwnum=$(( broadcast - 1 ))
    fi
    echo "$(( (gwnum>>24)&255 )).$(( (gwnum>>16)&255 )).$(( (gwnum>>8)&255 )).$(( gwnum&255 ))"
}

gen_wpa_enterprise_conf() {
    ssid="${1}"
    pass="${2}"
    identity="${3}"
    eap="${4:-PEAP}"
    phase2="${5}"
    anonymous_identity="${6}"
    ca_cert="${7}"
    domain_suffix_match="${8}"
    client_cert="${9}"
    private_key="${10}"
    private_key_passwd="${11}"
    eap=$(sanitize_wpa_token "$eap")
    case "$eap" in
    PEAP | TTLS)
        if [ -z "$phase2" ]; then
            phase2="auth=MSCHAPV2"
        fi
        ;;
    *)
        phase2=""
        ;;
    esac

    echo "ctrl_interface=/var/run/wpa_supplicant"
    echo "ap_scan=1"
    echo "fast_reauth=1"
    echo ""
    echo "network={"
    append_wpa_field "ssid" "$ssid"
    echo "    key_mgmt=WPA-EAP"
    echo "    eap=${eap}"
    append_wpa_field "identity" "$identity"
    append_wpa_field "password" "$pass"
    append_wpa_field "phase2" "$phase2"
    append_wpa_field "anonymous_identity" "$anonymous_identity"
    append_wpa_field "ca_cert" "$ca_cert"
    append_wpa_field "client_cert" "$client_cert"
    append_wpa_field "private_key" "$private_key"
    append_wpa_field "private_key_passwd" "$private_key_passwd"
    append_wpa_field "domain_suffix_match" "$domain_suffix_match"
    echo "}"
}

gen_hostapd_conf() {
    ssid="${1}"
    pass="${2}"
    echo "ctrl_interface=/var/run/hostapd"
    echo "ctrl_interface_group=0"
    echo "ssid=${ssid}"
    echo "hw_mode=g"
    echo "channel=1"
    echo "beacon_int=100"
    echo "dtim_period=2"
    echo "max_num_sta=255"
    echo "rts_threshold=-1"
    echo "fragm_threshold=-1"
    echo "macaddr_acl=0"
    echo "auth_algs=3"
    echo "wpa=2"
    echo "wpa_passphrase=${pass}"
    echo "ieee80211n=1"
}

gen_udhcpd_conf() {
    interface=${1}
    ipv4_prefix=${2}
    echo "start ${ipv4_prefix}.100"
    echo "end ${ipv4_prefix}.200"
    echo "interface ${interface}"
    echo "pidfile /var/run/udhcpd.${interface}.pid"
    echo "lease_file /var/lib/misc/udhcpd.${interface}.leases"
    echo "option subnet 255.255.255.0"
    echo "option lease 864000"
}

gen_dnsmasq_conf() {
    ipv4_prefix=${1}
    echo "bind-interfaces"
    echo "interface=wlan0"
    echo "address=/config.kvm/${ipv4_prefix}.1"
    echo "no-hosts"
    echo "dhcp-range=${ipv4_prefix}.2,${ipv4_prefix}.254"
    echo "dhcp-option=6,${ipv4_prefix}.1"
    echo "dhcp-option=3,${ipv4_prefix}.1"
    echo "dhcp-authoritative"
}

start() {
    echo "wifi mode: sta"
    ssid=""
    pass=""
    mode="psk"
    identity=""
    eap="PEAP"
    phase2="auth=MSCHAPV2"
    anonymous_identity=""
    ca_cert=""
    client_cert=""
    private_key=""
    private_key_passwd=""
    domain_suffix_match=""
    if [ -e /boot/wifi.ssid ] && [ -e /boot/wifi.pass ]; then
        echo "Updating WiFi credentials from /boot to /etc/kvm/"

        rm -f /etc/kvm/wifi.ssid /etc/kvm/wifi.pass /etc/kvm/wifi.mode

        mv /boot/wifi.ssid /etc/kvm/wifi.ssid
        mv /boot/wifi.pass /etc/kvm/wifi.pass

        chown root:root /etc/kvm/wifi.ssid /etc/kvm/wifi.pass
        chmod 644 /etc/kvm/wifi.ssid
        chmod 600 /etc/kvm/wifi.pass
    fi
    if [ -e /etc/kvm/wifi.ssid ]; then
        ssid=$(cat /etc/kvm/wifi.ssid)
    fi
    if [ -e /etc/kvm/wifi.pass ]; then
        pass=$(cat /etc/kvm/wifi.pass)
    fi
    if [ -e /etc/kvm/wifi.mode ]; then
        mode=$(cat /etc/kvm/wifi.mode)
    fi
    if [ -e /etc/kvm/wifi.identity ]; then
        identity=$(cat /etc/kvm/wifi.identity)
    fi
    if [ -e /etc/kvm/wifi.eap ]; then
        eap=$(cat /etc/kvm/wifi.eap)
    fi
    if [ -e /etc/kvm/wifi.phase2 ]; then
        phase2=$(cat /etc/kvm/wifi.phase2)
    fi
    if [ -e /etc/kvm/wifi.anonymous_identity ]; then
        anonymous_identity=$(cat /etc/kvm/wifi.anonymous_identity)
    fi
    if [ -e /etc/kvm/wifi.ca_cert ]; then
        ca_cert=$(cat /etc/kvm/wifi.ca_cert)
    fi
    if [ -e /etc/kvm/wifi.client_cert ]; then
        client_cert=$(cat /etc/kvm/wifi.client_cert)
    fi
    if [ -e /etc/kvm/wifi.private_key ]; then
        private_key=$(cat /etc/kvm/wifi.private_key)
    fi
    if [ -e /etc/kvm/wifi.private_key_passwd ]; then
        private_key_passwd=$(cat /etc/kvm/wifi.private_key_passwd)
    fi
    if [ -e /etc/kvm/wifi.domain_suffix_match ]; then
        domain_suffix_match=$(cat /etc/kvm/wifi.domain_suffix_match)
    fi

    case "$mode" in
    enterprise | 8021x | wpa-eap)
        gen_wpa_enterprise_conf "$ssid" "$pass" "$identity" "$eap" "$phase2" "$anonymous_identity" "$ca_cert" "$domain_suffix_match" "$client_cert" "$private_key" "$private_key_passwd" >/etc/wpa_supplicant.conf
        ;;
    *)
        echo "ctrl_interface=/var/run/wpa_supplicant" >/etc/wpa_supplicant.conf
        wpa_passphrase "$ssid" "$pass" >>/etc/wpa_supplicant.conf
        ;;
    esac
    chmod 600 /etc/wpa_supplicant.conf
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    ifconfig wlan0 up
    ip route del default || true
    ip addr flush dev wlan0
    if [ -e "$WIFI_STATIC_CONFIG" ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            line=$(clean_line "$line")
            [ -z "$line" ] && continue
            set -- $line
            inet="$1"
            gw="$2"
            [ -z "$inet" ] && continue
            case "$inet" in
                */*)
                    netid_check=${inet#*/}
                    if ! echo "$netid_check" | grep -qE '^[0-9]+$' || [ $netid_check -lt 1 ] 2>/dev/null || [ $netid_check -gt 32 ] 2>/dev/null; then
                        inet="${inet%/*}/16"
                    fi
                    ;;
                *)
                    inet="$inet/16"
                    ;;
            esac
            addr=${inet%/*}
            netid=${inet#*/}
            [ -z "$gw" ] && gw=$(calc_gw "$addr" "$netid")
            arping -Dqc2 -Iwlan0 "$addr" || continue
            ip a add "$inet" brd + dev wlan0
            ip r add default via "$gw" dev wlan0
            echo -e "nameserver $gw" >> /etc/resolv.conf
            break
        done < "$WIFI_STATIC_CONFIG"

        ip a show dev wlan0 | grep inet > /dev/null || {
            udhcpc -i wlan0 -t 3 -T 1 -A 5 -b -p /run/udhcpc.wlan0.pid &>/dev/null
            ip a show dev wlan0 | grep inet > /dev/null
        } || {
            inet=192.168.90.1/22
            addr=${inet%/*}
            ip a add "$inet" brd + dev wlan0
        } || exit 1
    else
        (udhcpc -i wlan0 -t 10 -T 1 -A 5 -b -p /run/udhcpc.wlan0.pid) &
    fi
}

ap_start() {
    echo "wifi mode: ap"
    id2=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 2))
    id3=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 4 | tail -c 2))
    if [ "$id2" = "$id3" ]; then
        id2=$((id2 + 1))
    fi
    if [ "$id2" -ge 255 ]; then
        id2=253
    fi
    if [ "$id3" -ge 255 ]; then
        id3=254
    fi
    ssid=""
    pass=""
    if [ -e /kvmapp/kvm/ap.ssid ]; then
        ssid=$(cat /kvmapp/kvm/ap.ssid)
    fi
    if [ -e /kvmapp/kvm/ap.pass ]; then
        pass=$(cat /kvmapp/kvm/ap.pass)
    fi
    gen_hostapd_conf "$ssid" "$pass" >/etc/hostapd.conf
    ipv4_prefix=10.$id3.$id2
    if [ ! -e /etc/udhcpd.wlan0.conf ]; then
        gen_udhcpd_conf wlan0 "${ipv4_prefix}" >/etc/udhcpd.wlan0.conf
    fi
    # gen_dnsmasq_conf "${ipv4_prefix}"  > /etc/dnsmasq.conf

    # iptables --policy INPUT ACCEPT
    # iptables --policy FORWARD ACCEPT
    # iptables --policy OUTPUT ACCEPT
    # iptables -F
    # iptables -t nat -F
    # iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 53 -j DNAT --to ${ipv4_prefix}.1

    ifconfig wlan0 up
    ip route del default || true
    ip add flush dev wlan0
    ip addr add $ipv4_prefix.1/24 dev wlan0
    # dnsmasq --pid-file=/tmp/dnsmasq.run -C /etc/dnsmasq.conf
    hostapd -B -i wlan0 /etc/hostapd.conf
    udhcpd -S /etc/udhcpd.wlan0.conf

    if [ ! -f "$APFLAG_FILE" ]; then
        touch "$APFLAG_FILE"
    fi

}

stop() {
    ps -ef | grep hostapd | grep -v grep | awk '{print $1}' | xargs kill -2 || true
    ps -ef | grep "udhcpd -S /etc/udhcpd.wlan0.conf" | grep -v grep | awk '{print $1}' | xargs kill -2 || true
    killall wpa_supplicant || true
    if [ -e /run/udhcpc.wlan0.pid ]; then
        kill $(cat /run/udhcpc.wlan0.pid) || true
        rm -f /run/udhcpc.wlan0.pid
    fi
    if [ -e /var/run/udhcpd.wlan0.pid ]; then
        kill $(cat /var/run/udhcpd.wlan0.pid) || true
        rm -f /var/run/udhcpd.wlan0.pid
    fi
    if [ -e /tmp/dnsmasq.run ]; then
        kill $(cat /tmp/dnsmasq.run) || true
        rm -f /tmp/dnsmasq.run
    fi
    # if [ -e /etc/wpa_supplicant.conf]
    # then
    # 	echo > /etc/wpa_supplicant.conf
    # fi
    airmon-ng stop wlan0mon || true

    if [ -f "$APFLAG_FILE" ]; then
        rm "$APFLAG_FILE"
    fi
}

restart() {
    stop
    start
}

if [ "${1}" = "start" ]; then
    start
elif [ "${1}" = "stop" ]; then
    stop
elif [ "${1}" = "ap" ]; then
    stop
    ap_start
elif [ "${1}" = "restart" ]; then
    restart
fi
