#!/bin/sh
#
# mouse-jiggler        Starts mouse-jiggler.
#

PIDFILE="/var/run/mouse-jiggler.pid"

start() {
    if [ ! -f "$PIDFILE" ];then
        echo "Starting Mouse Jiggler"
        (
        status=true
        while true;do
            if [ "$status" = true ];then
                echo -ne \\x00\\x1\\x00\\x00 > /dev/hidg1            
                status=false
            else
                echo -ne \\x1\\x00\\x00\\x00 > /dev/hidg1            
                status=true
            fi
            sleep 60
        done
        ) >/dev/null 2>&1 &
        echo $! > "$PIDFILE"
    else
        echo "Mouse Jiggler already started"
    fi
}

stop() {
  echo "Stopping Mouse Jiggler"
    [ -f "$PIDFILE" ] && kill $(cat "$PIDFILE") && rm -f "$PIDFILE"
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0