allowBuilds:
  bufferutil: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  utf-8-validate: set this to true or false
